### PR TITLE
Issue #31 - Adds webcompat report option to the context menu for chrme and opera

### PR DESCRIPTION
**Pull request by AkhilHector**
Signed-off-by: AkhilHector <akhilhector.1@gmail.com>

### CODE REVIEW

**Comment by miketaylr** [comment]
Looks good -- can we also bump the version in manifest.json from 0.3 to 0.4 please?

**Comment by AkhilHector** [comment]
sure @miketaylr no problem

**Comment by miketaylr** [comment]
r+

**Pull request merged**
