### PR TITLE
Global command np for running eslint for all add-on

### LINKED ISSUE #45: Add an npm top level command for running eslint on all add-on folders
The command must eslint the following sub-folders : 
- `firefox`
- `chrome`
- `opera`

PS  : The command must run from the project root

### PR DESCRIPTION
**Pull request by magsout**
Closes #45 

r? @AkhilHector 

@miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
👍

**Comment by miketaylr** [comment]
@AkhilHector did you want to review this PR? Or should I?

**Comment by AkhilHector** [comment]
@miketaylr yes can i review ?

**Comment by miketaylr** [comment]
@AkhilHector sure thing!

**Comment by miketaylr** [comment]
> Please squash the two commits and send them as one

IMO, two commits here is OK, since they're atomic.

**Comment by AkhilHector** [comment]
@miketaylr oh ok

**Comment by magsout** [comment]
oooooops...

@AkhilHector  

last commit updated. I had safari and firefox mobile, but don't know if it's necessary.

**Comment by AkhilHector** [comment]
@miketaylr I have a question, the current scenario is setup in such a way that as soon as you run "npm run eslint" it subsequently goes into each directory and performs an eslint. So "chrome, firefox, firefox-mobile, opera, safari" is the order in which this happens. So right now per say If there is an error in chrome then it pops out an error and forgets to eslint the remaining ones. What do you think is suggestible an eslintrc or a dedicated eslint.js file which handles all these operations ?

**Comment by miketaylr** [comment]
Hmm... good question @AkhilHector. I'm not actually sure if I have a preference. Even if the process bailed because it hit an error, that would be useful. But it would be nicer if it could give a report of all failures for all add-ons. What do you think?

**Comment by AkhilHector** [comment]
That's what i actually thought if it can report the failures of all the add-ons then it would be a bit beneficial.

**Comment by miketaylr** [comment]
👍

**Comment by AkhilHector** [comment]
@magsout can you please implement this ?
PS : Basically please remove the .eslintrc and have a eslint.js that can basically catch all the errors and report them.

**Comment by miketaylr** [comment]
(FWIW, I think @magsout is a bit swamped with work lately. @AkhilHector if you'd like to take over the PR, I don't think he'd mind)

**Comment by AkhilHector** [comment]
@miketaylr ok sure

**Comment by AkhilHector** [comment]
@magsout keeping in mind the above changes, i have closed this PR

**Comment by magsout** [comment]
ok

**Pull request closed without merging**
