### PR TITLE
Fixes #35 - Renamed firefox-webext directory, removed firefox directory

### LINKED ISSUE #35: Remove firefox directory
We moved to a WebExtension, which is shipping now, so we can just get rid of the old one. And then we can rename firefox-webext to just firefox.

### PR DESCRIPTION
**Pull request by AkhilHector**
Signed-off-by: AkhilHector <akhilhector.1@gmail.com>

### CODE REVIEW

**Comment by miketaylr** [comment]
LGTM.

**Comment by miketaylr** [comment]
Oops, pulled the trigger too fast. Can you send a follow-up PR updated the README:

https://github.com/webcompat/webcompat-reporter-extensions#note

**Comment by AkhilHector** [comment]
Ok

**Pull request merged**
